version: '3.8'

services:
  kodi-nowplaying:
    build: .
    container_name: kodi-nowplaying
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    volumes:
      - ./tmp:/tmp
